### ISSUE TITLE
AttributeError: 'module' object has no attribute 'randint'

### ISSUE THREAD

**Issue by robertio** [astoeckel/femtosip#3]
Hi Andreas,

Other issue solved, so i closed that issue.

But now i faced another error message:

```
>>> import femtosip
>>>sip = femtosip.SIP('doorbell','pw','192.168.188.1','5060','door')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "femtosip.py", line 267, in __init__
  File "femtosip.py", line 298, in make_random_digits
AttributeError: 'module' object has no attribute 'randint'
>>> 
```

This is the 2 functions having line 276 and 298: 

```
 def __init__(self, user, password, gateway, port, display_name=None):
        # Copy the parameters
        self.user = user
        self.password = password
        self.local_ip, self.local_port = None, None # To be read dynamically
        self.gateway = gateway
        self.port = port
        self.display_name = display_name

        # Initilise the session parameters
        self.seq = 0
        self.session_id = self.make_random_digits(4);                         #Line 276
        self.session_version = self.make_random_digits(4);

@staticmethod
    def make_random_digits(len=10):
        res = '';
        for i in range(len):
            res += str(random.randint(1 if i == 0 else 0, 9))                         #Line 298
        return res
```

Can you please advise how to resolve them?

best regards,
Robert

**Comment by astoeckel** [comment]
Well, you'll have to read the documentation of the Micropython runtime you are using and find some function that generates random numbers for you. I don't know anything about Micropython and can't be of much help here.

In general, from what I understand, you should expect to replace some of the standard Python libraries used in the code by their corresponding Micropython counterparts; you may have to slightly adapt the code in order to do that.

**Comment by robertio** [comment]
Thanks Andreas, 

Micropython has libraries: [https://docs.micropython.org/en/v1.15/library/index.html](url)
Unfortunately Im not very good at Python programming, so I dont understand fully, this lib names should start u... in micropython libs.
But i didnt use the lib name started u.... 
and the original lib names in Import lines were successfull on ESP. Lib names are binded??

`import collections
import hashlib
import socket
import select
import random
import re
import time
import logging`

At the same time i start to go to another direction too: 
In this scenario: ESP will only work as button and send event to the Home Assistant (HA) - (in sort: it is kind of server for IOT devices). 
In this scenario: HA will trigger SIP call. (HA is installed on my NAS -linux- so easyly can run femtosip to call)

i dont know which of the solution will work.
But many thanks for your support.

**Comment by astoeckel** [comment]
Closing this for now; I don't think that it will be easy to port the code to Micropython.
