### ISSUE TITLE
Timeout while waiting for server response

### ISSUE THREAD

**Issue by m-kloeckner** [astoeckel/femtosip#4]
First off: Thank you very much for developing this! I'm using your script for a few months now to trigger my home office phone when someone is at the door. It's very reliable.

I only had to make a small adjustment in line 503. My old Gigaset S685IP is not responding fast enough, so 1s timeout was too low. Should this be just increased or should this be made configurable?

https://github.com/astoeckel/femtosip/blob/dab4b59c939a361f9201cc82fcc0d328c80be6aa/femtosip.py#L503-L504

**Comment by astoeckel** [comment]
Thank you for your feedback, glad to hear that you found it useful!

I agree that the 1.0 second timeout is too low. Optimally, this would be configurable with a default of about 5.0 to 10.0 seconds, I guess.

**Comment by tobwen** [comment]
Raising this value also makes it work with my Asterisk PBX. I think about exposing it to a switch.

**Comment by astoeckel** [comment]
This has been fixed by the PR referenced above.
