### ISSUE TITLE
Video call 

### ISSUE THREAD

**Issue by pergolafabio** [astoeckel/femtosip#9]
Hey @astoeckel , just found this repo, looks interesting...
I was wondering if I could initiate a video call, with maybe rtsp as a source/path or a v4l2loopback device?

My project is to make a door intercom, that doent have a camera... So I can your client make the call, creating a conference and inviting the door intercom into the conference...

Thnx for feedback

**Comment by astoeckel** [comment]
Support for establishing an actual RTSP stream is probably not too difficult; if I remember correctly, when I initially developed the code I was able to dump the packets from the RTP stream advertised by the calling party and play them back.

However, providing this is out-of-scope for this project.

But please feel free to fork and implement the required code yourself, it is surely a nice coding project!
